"""init tables

Revision ID: b13356244aea
Revises:
Create Date: 2026-01-23 09:29:06.142330

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "b13356244aea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("alias_id", sa.String(length=64), nullable=True, comment="应用标识"),
        sa.Column("api_key", sa.String(length=50), nullable=False),
        sa.Column("api_secret", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "is_tenant",
            sa.SmallInteger(),
            nullable=True,
            server_default="0",
            comment="是否为租户app\n0: 否\n1: 是",
        ),
        sa.Column(
            "source",
            sa.SmallInteger(),
            nullable=True,
            server_default="0",
            comment="租户归属，采用二进制位权的十进制表示。如：1: 星辰平台, 2: 开放平台, 4: AIUI",
        ),
        sa.Column(
            "actual_source",
            sa.SmallInteger(),
            nullable=True,
            server_default="0",
            comment="应用实际归属",
        ),
        sa.Column(
            "plat_release_auth",
            sa.SmallInteger(),
            nullable=True,
            server_default="0",
            comment="针对租户账户，提供平台授权权限。值为source或值",
        ),
        sa.Column(
            "status",
            sa.SmallInteger(),
            nullable=True,
            server_default="1",
            comment="应用状态\n0: 禁用\n1: 启用",
        ),
        sa.Column("audit_policy", sa.SmallInteger(), nullable=True, server_default="0"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建人"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新人"),
        sa.Column("create_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="app 信息",
    )
    op.create_index("alias_id", "app", ["alias_id"], unique=True)
    op.create_index("idx_appid", "app", ["alias_id"], unique=False)
    op.create_table(
        "app_source",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.SmallInteger(),
            nullable=False,
            comment="租户归属，采用二进制位权的十进制表示。如：1: 星辰平台, 2: 开放平台, 4: AIUI",
        ),
        sa.Column(
            "source_id", sa.String(length=32), nullable=False, comment="租户源ID"
        ),
        sa.Column("description", sa.String(length=16), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flow",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True, server_default="0"),
        sa.Column("name", sa.String(length=128), nullable=False, comment="协议名称"),
        sa.Column("data", sa.Text(), nullable=True, comment="编排标准协议"),
        sa.Column("release_data", sa.Text(), nullable=True, comment="发布后的数据"),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "version",
            sa.String(length=128),
            nullable=True,
            server_default="",
            comment="协议版本",
        ),
        sa.Column(
            "release_status", sa.SmallInteger(), nullable=True, comment="发布状态或值"
        ),
        sa.Column("app_id", sa.String(length=255), nullable=True, comment="app_id"),
        sa.Column(
            "source",
            sa.SmallInteger(),
            nullable=True,
            server_default="0",
            comment="来源",
        ),
        sa.Column(
            "tag",
            sa.Integer(),
            nullable=True,
            comment="标记工作流标签 0：无标签；1：对照组",
        ),
        sa.Column(
            "create_by",
            sa.BigInteger(),
            nullable=False,
            server_default="0",
            comment="创建人",
        ),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新人"),
        sa.Column(
            "create_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "update_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uniq_group_id_version", "flow", ["group_id", "version"], unique=True
    )
    op.create_index("idx_flow_name", "flow", ["name"], unique=False)
    op.create_table(
        "license",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("app_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.SmallInteger(),
            nullable=False,
            server_default="1",
            comment="授权状态\n0: 禁用\n1: 启用",
        ),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("lic_uk_appid_gid", "license", ["app_id", "group_id"], unique=True)
    op.create_index(
        "idx_app_id_group_id", "license", ["app_id", "group_id"], unique=False
    )
    op.create_table(
        "workflow_node_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("node_id", sa.String(length=255), nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=True),
        sa.Column("chat_id", sa.String(length=255), nullable=True),
        sa.Column("raw_question", sa.Text(), nullable=True),
        sa.Column("raw_answer", sa.Text(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column("flow_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("chat_id", "workflow_node_history", ["chat_id"], unique=False)
    op.create_index("node_id", "workflow_node_history", ["node_id"], unique=False)
    op.create_index("uid", "workflow_node_history", ["uid"], unique=False)
    # ### end Alembic commands ###

    # Insert initial data
    app_table = sa.table(
        "app",
        sa.column("id", sa.BigInteger),
        sa.column("name", sa.String),
        sa.column("alias_id", sa.String),
        sa.column("api_key", sa.String),
        sa.column("api_secret", sa.String),
        sa.column("description", sa.String),
        sa.column("is_tenant", sa.SmallInteger),
        sa.column("source", sa.SmallInteger),
        sa.column("actual_source", sa.SmallInteger),
        sa.column("plat_release_auth", sa.SmallInteger),
        sa.column("status", sa.SmallInteger),
        sa.column("audit_policy", sa.SmallInteger),
        sa.column("create_by", sa.BigInteger),
        sa.column("update_by", sa.BigInteger),
        sa.column("create_at", sa.DateTime),
        sa.column("update_at", sa.DateTime),
    )

    app_source_table = sa.table(
        "app_source",
        sa.column("id", sa.BigInteger),
        sa.column("source", sa.SmallInteger),
        sa.column("source_id", sa.String),
        sa.column("description", sa.String),
        sa.column("create_at", sa.DateTime),
        sa.column("update_at", sa.DateTime),
    )

    # Insert default app
    op.bulk_insert(
        app_table,
        [
            {
                "id": 1,
                "name": "星辰",
                "alias_id": "680ab54f",
                "api_key": "7b709739e8da44536127a333c7603a83",
                "api_secret": "NjhmY2NmM2NkZDE4MDFlNmM5ZjcyZjMy",
                "description": "星辰",
                "is_tenant": 1,
                "source": 1,
                "actual_source": 1,
                "plat_release_auth": 1,
                "status": 1,
                "audit_policy": 0,
                "create_by": 1,
                "update_by": 1,
                "create_at": datetime(2025, 9, 20, 14, 10, 48),
                "update_at": datetime(2025, 9, 20, 14, 10, 51),
            }
        ],
    )

    # Insert default app_source
    op.bulk_insert(
        app_source_table,
        [
            {
                "id": 1,
                "source": 1,
                "source_id": "admin",
                "description": "星辰",
                "create_at": datetime(2025, 10, 11, 9, 21, 11),
                "update_at": datetime(2025, 10, 11, 9, 21, 11),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete initial data before dropping tables
    op.execute("DELETE FROM app_source WHERE id = 1")
    op.execute("DELETE FROM app WHERE id = 1")

    # Drop workflow_node_history indexes
    op.drop_index("uid", table_name="workflow_node_history")
    op.drop_index("node_id", table_name="workflow_node_history")
    op.drop_index("chat_id", table_name="workflow_node_history")
    op.drop_table("workflow_node_history")

    # Drop license indexes
    op.drop_index("idx_app_id_group_id", table_name="license")
    op.drop_index("lic_uk_appid_gid", table_name="license")
    op.drop_table("license")

    # Drop flow indexes
    op.drop_index("idx_flow_name", table_name="flow")
    op.drop_index("uniq_group_id_version", table_name="flow")
    op.drop_table("flow")

    op.drop_table("app_source")

    # Drop app indexes
    op.drop_index("idx_appid", table_name="app")
    op.drop_index("alias_id", table_name="app")
    op.drop_table("app")
    # ### end Alembic commands ###
