"""init tables

Revision ID: b13356244aea
Revises:
Create Date: 2026-01-23 09:29:06.142330

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "b13356244aea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alias_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_secret", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_tenant", sa.Integer(), nullable=False),
        sa.Column("source", sa.Integer(), nullable=False),
        sa.Column("actual_source", sa.Integer(), nullable=False),
        sa.Column("plat_release_auth", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("audit_policy", sa.Integer(), nullable=False),
        sa.Column("create_by", sa.Integer(), nullable=False),
        sa.Column("update_by", sa.Integer(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("alias_id", "app", ["alias_id"], unique=True)
    op.create_index("idx_appid", "app", ["alias_id"], unique=False)
    op.create_table(
        "app_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Integer(), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "flow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("release_data", sa.JSON(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release_status", sa.Integer(), nullable=False),
        sa.Column("app_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sa.Integer(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("tag", sa.Integer(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uniq_group_id_version", "flow", ["group_id", "version"], unique=True
    )
    op.create_index("idx_flow_name", "flow", ["name"], unique=False)
    op.create_table(
        "license",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("update_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("lic_uk_appid_gid", "license", ["app_id", "group_id"], unique=True)
    op.create_index(
        "idx_app_id_group_id", "license", ["app_id", "group_id"], unique=False
    )
    op.create_table(
        "workflow_node_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "node_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("uid", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "chat_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("raw_question", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.Column(
            "flow_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("chat_id", "workflow_node_history", ["chat_id"], unique=False)
    op.create_index("node_id", "workflow_node_history", ["node_id"], unique=False)
    op.create_index("uid", "workflow_node_history", ["uid"], unique=False)
    # ### end Alembic commands ###

    # Insert initial data
    app_table = sa.table(
        "app",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("alias_id", sa.String),
        sa.column("api_key", sa.String),
        sa.column("api_secret", sa.String),
        sa.column("description", sa.String),
        sa.column("is_tenant", sa.Integer),
        sa.column("source", sa.Integer),
        sa.column("actual_source", sa.Integer),
        sa.column("plat_release_auth", sa.Integer),
        sa.column("status", sa.Integer),
        sa.column("audit_policy", sa.Integer),
        sa.column("create_by", sa.Integer),
        sa.column("update_by", sa.Integer),
        sa.column("create_at", sa.DateTime),
        sa.column("update_at", sa.DateTime),
    )

    app_source_table = sa.table(
        "app_source",
        sa.column("id", sa.Integer),
        sa.column("source", sa.Integer),
        sa.column("source_id", sa.String),
        sa.column("description", sa.String),
        sa.column("create_at", sa.DateTime),
        sa.column("update_at", sa.DateTime),
    )

    # Insert default app
    op.bulk_insert(
        app_table,
        [
            {
                "id": 1,
                "name": "星辰",
                "alias_id": "680ab54f",
                "api_key": "7b709739e8da44536127a333c7603a83",
                "api_secret": "NjhmY2NmM2NkZDE4MDFlNmM5ZjcyZjMy",
                "description": "星辰",
                "is_tenant": 1,
                "source": 1,
                "actual_source": 1,
                "plat_release_auth": 1,
                "status": 1,
                "audit_policy": 0,
                "create_by": 1,
                "update_by": 1,
                "create_at": datetime(2025, 9, 20, 14, 10, 48),
                "update_at": datetime(2025, 9, 20, 14, 10, 51),
            }
        ],
    )

    # Insert default app_source
    op.bulk_insert(
        app_source_table,
        [
            {
                "id": 1,
                "source": 1,
                "source_id": "admin",
                "description": "星辰",
                "create_at": datetime(2025, 10, 11, 9, 21, 11),
                "update_at": datetime(2025, 10, 11, 9, 21, 11),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete initial data before dropping tables
    op.execute("DELETE FROM app_source WHERE id = 1")
    op.execute("DELETE FROM app WHERE id = 1")

    # Drop workflow_node_history indexes
    op.drop_index("uid", table_name="workflow_node_history")
    op.drop_index("node_id", table_name="workflow_node_history")
    op.drop_index("chat_id", table_name="workflow_node_history")
    op.drop_table("workflow_node_history")

    # Drop license indexes
    op.drop_index("idx_app_id_group_id", table_name="license")
    op.drop_index("lic_uk_appid_gid", table_name="license")
    op.drop_table("license")

    # Drop flow indexes
    op.drop_index("idx_flow_name", table_name="flow")
    op.drop_index("uniq_group_id_version", table_name="flow")
    op.drop_table("flow")

    op.drop_table("app_source")

    # Drop app indexes
    op.drop_index("idx_appid", table_name="app")
    op.drop_index("alias_id", table_name="app")
    op.drop_table("app")
    # ### end Alembic commands ###
