package com.iflytek.astron.console.toolkit.service.bot;

import com.iflytek.astron.console.commons.constant.ResponseEnum;
import com.iflytek.astron.console.commons.exception.BusinessException;
import com.iflytek.astron.console.commons.util.SseEmitterUtil;
import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.core.http.StreamResponse;
import com.openai.models.chat.completions.ChatCompletion;
import com.openai.models.chat.completions.ChatCompletionChunk;
import com.openai.models.chat.completions.ChatCompletionCreateParams;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.UUID;

/**
 * OpenAI model processing service implementation
 */
@Slf4j
@Service
public class OpenAiModelProcessService {

    @Value("${ai-ability.chat.api-key}")
    private String apiKey;

    /**
     * Base URL should not include /chat/completions path OpenAI SDK will automatically append the
     * endpoint path
     */
    @Value("${ai-ability.chat.base-url}")
    private String baseUrl;

    @Value("${ai-ability.chat.model}")
    private String model;

    private OpenAIClient client;

    /**
     * Initialize OpenAI client after properties are set
     */
    @PostConstruct
    public void init() {
        this.client = OpenAIOkHttpClient.builder()
                .apiKey(apiKey)
                .baseUrl(baseUrl)
                .build();
        log.info("OpenAI client initialized with base URL: {}", baseUrl);
    }

    /**
     * Non-streaming call to OpenAI API
     *
     * @param prompt User input prompt
     * @return Complete response content generated by the model
     */
    public String processNonStreaming(String prompt) {
        log.info("Starting non-streaming OpenAI API call, prompt: {}", prompt);

        try {
            // Build request parameters
            ChatCompletionCreateParams params = ChatCompletionCreateParams.builder()
                    .model(model)
                    .addUserMessage(prompt)
                    .build();

            // Call API
            ChatCompletion completion = client.chat().completions().create(params);

            // Extract response content
            String content = completion.choices().getFirst().message().content().orElse("");

            log.info("Non-streaming call completed, response length: {}", content.length());
            return content;

        } catch (Exception e) {
            log.error("Non-streaming OpenAI API call failed", e);
            throw new BusinessException(ResponseEnum.OPEN_AI_API_ERROR);
        }
    }

    /**
     * Streaming call to OpenAI API
     *
     * @param prompt User input prompt
     * @return SseEmitter object for real-time streaming response data
     */
    public SseEmitter processStreaming(String prompt) {
        log.info("Starting streaming OpenAI API call, prompt: {}", prompt);

        // Create SseEmitter
        SseEmitter emitter = SseEmitterUtil.createSseEmitter();
        String streamId = UUID.randomUUID().toString();

        // Process streaming response asynchronously
        Thread.startVirtualThread(() -> {
            try {
                // Build streaming request parameters
                ChatCompletionCreateParams params = ChatCompletionCreateParams.builder()
                        .model(model)
                        .addUserMessage(prompt)
                        .build();

                // Call streaming API and process response
                try (StreamResponse<ChatCompletionChunk> streamResponse =
                        client.chat().completions().createStreaming(params)) {

                    streamResponse.stream()
                            .flatMap(chunk -> chunk.choices().stream())
                            .flatMap(choice -> choice.delta().content().stream())
                            .forEach(content -> {
                                // Check if stopped
                                if (SseEmitterUtil.isStreamStopped(streamId)) {
                                    log.info("Streaming call stopped");
                                    return;
                                }

                                // Send content to frontend
                                if (!content.isEmpty()) {
                                    SseEmitterUtil.sendData(emitter, content);
                                }
                            });
                }

                // Send end signal and complete
                SseEmitterUtil.sendEndAndComplete(emitter);
            } catch (Exception e) {
                log.error("Streaming OpenAI API call failed", e);
                SseEmitterUtil.completeWithError(emitter, "OpenAI API call failed: " + e.getMessage());
            }
        });

        return emitter;
    }
}
