package com.iflytek.astron.console.hub.service.bot;

import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

/**
 * OpenAI model processing service interface
 */
public interface OpenAiModelProcessService {

    /**
     * Non-streaming call to OpenAI API
     *
     * @param prompt User input prompt
     * @return Complete response content generated by the model
     */
    String processNonStreaming(String prompt);

    /**
     * Streaming call to OpenAI API
     *
     * @param prompt User input prompt
     * @return SseEmitter object for real-time streaming response data
     */
    SseEmitter processStreaming(String prompt);
}
