"""
Constants definition module containing various constants and configuration
parameters used in the project.
"""

import os

# env
ENVIRONMENT_KEY = "ENVIRONMENT"
Env = os.getenv(ENVIRONMENT_KEY)
ENV_PRODUCTION = "production"
ENV_PRERELEASE = "prerelease"
ENV_DEVELOPMENT = "development"

CONFIG_FILE_KEY = "CONFIG_FILE"

USE_POLARIS_KEY = "USE_POLARIS"
POLARIS_URL_KEY = "POLARIS_URL"
POLARIS_USERNAME_KEY = "POLARIS_USERNAME"
POLARIS_PASSWORD_KEY = "POLARIS_PASSWORD"
POLARIS_CLUSTER_KEY = "POLARIS_CLUSTER"

PROJECT_NAME_KEY = "PROJECT_NAME"
VERSION_KEY = "VERSION"

CONFIG_WATCH_INTERVAL_KEY = "CONFIG_WATCH_INTERVAL"
HOT_RELOAD_ENABLE_KEY = "HOT_RELOAD_ENABLE"

# service info
SERVICE_SUB_KEY = "SERVICE_SUB"
SERVICE_NAME_KEY = "SERVICE_NAME"
SERVICE_LOCATION_KEY = "SERVICE_LOCATION"
SERVICE_PORT_KEY = "SERVICE_PORT"
SERVICE_APP_KEY = "SERVICE_APP"

# log info
LOG_FILE_KEY = "LOG_FILE"
LOG_ROTATION_KEY = "LOG_ROTATION"
LOG_RETENTION_KEY = "LOG_RETENTION"
LOG_ENCODING_KEY = "LOG_ENCODING"
LOG_LEVEL_KEY = "LOG_LEVEL"
LOG_STDOUT_ENABLE_KEY = "LOG_STDOUT_ENABLE"

# middleware info
SAMPLE_RATE_KEY = "SAMPLE_RATE"
INCLUDE_PATHS_KEY = "INCLUDE_PATHS"

# aiohttp info
AIOHTTP_CLIENT_TOTAL_TIMEOUT_KEY = "AIOHTTP_CLIENT_TOTAL_TIMEOUT"
AIOHTTP_CLIENT_CONNECT_TIMEOUT_KEY = "AIOHTTP_CLIENT_CONNECT_TIMEOUT"
AIOHTTP_CLIENT_READ_TIMEOUT_KEY = "AIOHTTP_CLIENT_READ_TIMEOUT"
AIOHTTP_CLIENT_LIMIT_CONNECTOR_KEY = "AIOHTTP_CLIENT_LIMIT_CONNECTOR"
AIOHTTP_CLIENT_LIMIT_PER_HOST_CONNECTOR_KEY = "AIOHTTP_CLIENT_LIMIT_PER_HOST_CONNECTOR"
AIOHTTP_CLIENT_TTL_DNS_CACHE_CONNECTOR_KEY = "AIOHTTP_CLIENT_TTL_DNS_CACHE_CONNECTOR"
AIOHTTP_CLIENT_ENABLE_CLEANUP_CLOSED_CONNECTOR_KEY = (
    "AIOHTTP_CLIENT_ENABLE_CLEANUP_CLOSED_CONNECTOR"
)
AIOHTTP_CLIENT_TRUST_ENV_KEY = "AIOHTTP_CLIENT_TRUST_ENV"

# kafka info
KAFKA_ENABLE_KEY = "KAFKA_ENABLE"
KAFKA_SERVERS_KEY = "KAFKA_SERVERS"
KAFKA_TIMEOUT_KEY = "KAFKA_TIMEOUT"
KAFKA_TOPIC_KEY = "KAFKA_TOPIC"
KAFKA_QUEUE_MAX_SIZE_KEY = "KAFKA_QUEUE_MAX_SIZE"
KAFKA_ACKS_KEY = "KAFKA_ACKS"
KAFKA_LINGER_MS_KEY = "KAFKA_LINGER_MS"
KAFKA_RETRY_INTERVAL_KEY = "KAFKA_RETRY_INTERVAL"
KAFKA_RETRY_BACKOFF_MS_KEY = "KAFKA_RETRY_BACKOFF_MS"
KAFKA_DRAIN_TIMEOUT_KEY = "KAFKA_DRAIN_TIMEOUT"

# otlp info
OTLP_ENABLE_KEY = "OTLP_ENABLE"
OTLP_DC_KEY = "OTLP_DC"
OTLP_SERVICE_NAME_KEY = "OTLP_SERVICE_NAME"
OTLP_ENDPOINT_KEY = "OTLP_ENDPOINT"

OTLP_METRIC_EXPORT_INTERVAL_MILLIS_KEY = "OTLP_METRIC_EXPORT_INTERVAL_MILLIS"
OTLP_METRIC_EXPORT_TIMEOUT_MILLIS_KEY = "OTLP_METRIC_EXPORT_TIMEOUT_MILLIS"
OTLP_METRIC_TIMEOUT_KEY = "OTLP_METRIC_TIMEOUT"

OTLP_TRACE_TIMEOUT_KEY = "OTLP_TRACE_TIMEOUT"
OTLP_TRACE_MAX_QUEUE_SIZE_KEY = "OTLP_TRACE_MAX_QUEUE_SIZE"
OTLP_TRACE_SCHEDULE_DELAY_MILLIS_KEY = "OTLP_TRACE_SCHEDULE_DELAY_MILLIS"
OTLP_TRACE_MAX_EXPORT_BATCH_SIZE_KEY = "OTLP_TRACE_MAX_EXPORT_BATCH_SIZE"
OTLP_TRACE_EXPORT_TIMEOUT_MILLIS_KEY = "OTLP_TRACE_EXPORT_TIMEOUT_MILLIS"

# AI Tools info
AI_APP_ID_KEY = "AI_APP_ID"
AI_API_KEY_KEY = "AI_API_KEY"
AI_API_SECRET_KEY = "AI_API_SECRET"

# ocr info
OCR_LLM_WS_URL_KEY = "OCR_LLM_WS_URL"
OCR_LLM_HTTP_URL_KEY = "OCR_LLM_HTTP_URL"
OCR_LLM_THREAD_WORKS_KEY = "OCR_LLM_THREAD_WORKS"
OCR_LLM_SLEEP_TIME_KEY = "OCR_LLM_SLEEP_TIME"

# dial test info
INTERFACE_LIST_STR_KEY = "INTERFACE_LIST_STR"
INTERFACE_URL_SUFFIX = "_URL"
INTERFACE_METHOD_SUFFIX = "_METHOD"
INTERFACE_HEADERS_SUFFIX = "_HEADERS"
INTERFACE_PARAMS_SUFFIX = "_PARAMS"
INTERFACE_PAYLOAD_SUFFIX = "_PAYLOAD"
INTERFACE_SUCCESS_CODE_SUFFIX = "_SUCCESS_CODE"
INTERFACE_CALL_FREQUENCY_SUFFIX = "_CALL_FREQUENCY"

# image generate info
IMAGE_GENERATE_URL_KEY = "IMAGE_GENERATE_URL"

# image understanding info
IMAGE_UNDERSTANDING_URL_KEY = "IMAGE_UNDERSTANDING_URL"

# smart text to speech info
TTS_URL_KEY = "TTS_URL"

# speech evaluation info
ISE_URL_KEY = "ISE_URL"

# translation info
TRANSLATION_URL_KEY = "TRANSLATION_URL"
