"""init

Revision ID: 5c4f1b5ab83d
Revises:
Create Date: 2026-03-06 02:57:51.383278

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c4f1b5ab83d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tools_schema",
        "id",
        existing_type=mysql.BIGINT(),
        comment=None,
        existing_comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tools_schema",
        "app_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="Application ID",
        existing_comment="应用ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "tool_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="Tool ID",
        existing_comment="工具ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "name",
        existing_type=mysql.VARCHAR(length=128),
        comment="Tool name",
        existing_comment="工具名称",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        comment="Tool description",
        existing_comment="工具描述",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "open_api_schema",
        existing_type=mysql.TEXT(),
        comment="OpenAPI schema, JSON format",
        existing_comment="open api schema，json格式",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "create_at",
        existing_type=mysql.DATETIME(fsp=6),
        server_default=None,
        comment=None,
        existing_comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "update_at",
        existing_type=mysql.DATETIME(fsp=6),
        server_default=None,
        nullable=False,
        comment=None,
        existing_comment="更新时间",
    )
    op.alter_column(
        "tools_schema",
        "schema",
        existing_type=mysql.TEXT(),
        comment="Schema, JSON format",
        existing_comment="schema,json格式",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "version",
        existing_type=mysql.VARCHAR(length=32),
        server_default=None,
        comment="Version number",
        existing_comment="版本号",
        existing_nullable=False,
    )
    op.alter_column(
        "tools_schema",
        "is_deleted",
        existing_type=mysql.BIGINT(),
        server_default=None,
        comment="Is deleted",
        existing_comment="是否已删除",
        existing_nullable=False,
    )
    op.drop_table_comment("tools_schema", existing_comment="工具数据库表", schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "tools_schema", "工具数据库表", existing_comment=None, schema=None
    )
    op.alter_column(
        "tools_schema",
        "is_deleted",
        existing_type=mysql.BIGINT(),
        server_default=sa.text("'0'"),
        comment="是否已删除",
        existing_comment="Is deleted",
        existing_nullable=False,
    )
    op.alter_column(
        "tools_schema",
        "version",
        existing_type=mysql.VARCHAR(length=32),
        server_default=sa.text("'V1.0'"),
        comment="版本号",
        existing_comment="Version number",
        existing_nullable=False,
    )
    op.alter_column(
        "tools_schema",
        "schema",
        existing_type=mysql.TEXT(),
        comment="schema,json格式",
        existing_comment="Schema, JSON format",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "update_at",
        existing_type=mysql.DATETIME(fsp=6),
        server_default=sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)"),
        nullable=True,
        comment="更新时间",
    )
    op.alter_column(
        "tools_schema",
        "create_at",
        existing_type=mysql.DATETIME(fsp=6),
        server_default=sa.text("CURRENT_TIMESTAMP(6)"),
        comment="创建时间",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "open_api_schema",
        existing_type=mysql.TEXT(),
        comment="open api schema，json格式",
        existing_comment="OpenAPI schema, JSON format",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "description",
        existing_type=mysql.VARCHAR(length=512),
        comment="工具描述",
        existing_comment="Tool description",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "name",
        existing_type=mysql.VARCHAR(length=128),
        comment="工具名称",
        existing_comment="Tool name",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "tool_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="工具ID",
        existing_comment="Tool ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "app_id",
        existing_type=mysql.VARCHAR(length=32),
        comment="应用ID",
        existing_comment="Application ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tools_schema",
        "id",
        existing_type=mysql.BIGINT(),
        comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
